export const EQUIPMENTS = {
  stepmillMachine: "stepmill machine",
  ellipticalMachine: "elliptical machine",
  trapBar: "trap bar",
  tire: "tire",
  stationaryBike: "stationary bike",
  wheelRoller: "wheel roller",
  smithMachine: "smith machine",
  hammer: "hammer",
  skiergMachine: "skierg machine",
  roller: "roller",
  resistanceBand: "resistance band",
  bosuBall: "bosu ball",
  weighted: "weighted",
  olympicBarbell: "olympic barbell",
  kettlebell: "kettlebell",
  upperBodyErgometer: "upper body ergometer",
  sledMachine: "sled machine",
  ezBarbell: "ez barbell",
  dumbbell: "dumbbell",
  rope: "rope",
  barbell: "barbell",
  band: "band",
  stabilityBall: "stability ball",
  medicineBall: "medicine ball",
  assisted: "assisted",
  leverageMachine: "leverage machine",
  cable: "cable",
  bodyWeight: "body weight",
};
