export const MUSCLES = {
  shins: "shins",
  hands: "hands",
  sternocleidomastoid: "sternocleidomastoid",
  soleus: "soleus",
  innerThighs: "inner thighs",
  lowerAbs: "lower abs",
  gripMuscles: "grip muscles",
  abdominals: "abdominals",
  wristExtensors: "wrist extensors",
  wristFlexors: "wrist flexors",
  latissimusDorsi: "latissimus dorsi",
  upperChest: "upper chest",
  rotatorCuff: "rotator cuff",
  wrists: "wrists",
  groin: "groin",
  brachialis: "brachialis",
  deltoids: "deltoids",
  feet: "feet",
  ankles: "ankles",
  trapezius: "trapezius",
  rearDeltoids: "rear deltoids",
  chest: "chest",
  quadriceps: "quadriceps",
  back: "back",
  core: "core",
  shoulders: "shoulders",
  ankleStabilizers: "ankle stabilizers",
  rhomboids: "rhomboids",
  obliques: "obliques",
  lowerBack: "lower back",
  hipFlexors: "hip flexors",
  levatorScapulae: "levator scapulae",
  abductors: "abductors",
  serratusAnterior: "serratus anterior",
  traps: "traps",
  forearms: "forearms",
  delts: "delts",
  biceps: "biceps",
  upperBack: "upper back",
  spine: "spine",
  cardiovascularSystem: "cardiovascular system",
  triceps: "triceps",
  adductors: "adductors",
  hamstrings: "hamstrings",
  glutes: "glutes",
  pectorals: "pectorals",
  calves: "calves",
  lats: "lats",
  quads: "quads",
  abs: "abs",
};
