export const MUSCLES = {
  shins: "shins",
  hands: "hands",
  sternocleidomastoid: "sternocleidomastoid",
  soleus: "soleus",
  innerThighs: "inner thighs",
  lowerAbs: "lower abs",
  gripMuscles: "grip muscles",
  abdominals: "abdominals",
  wristExtensors: "wrist extensors",
  wristFlexors: "wrist flexors",
  latissimusDorsi: "latissimus dorsi",
  upperChest: "upper chest",
  rotatorCuff: "rotator cuff",
  wrists: "wrists",
  groin: "groin",
  brachialis: "brachialis",
  deltoids: "deltoids",
  feet: "feet",
  ankles: "ankles",
  trapezius: "trapezius",
  rearDeltoids: "rear deltoids",
  chest: "chest",
  quadriceps: "quadriceps",
  back: "back",
  core: "core",
  shoulders: "shoulders",
  ankleStabilizers: "ankle stabilizers",
  rhomboids: "rhomboids",
  obliques: "obliques",
  lowerBack: "lower back",
  hipFlexors: "hip flexors",
  levatorScapulae: "levator scapulae",
  abductors: "abductors",
  serratusAnterior: "serratus anterior",
  traps: "traps",
  forearms: "forearms",
  delts: "delts",
  biceps: "biceps",
  upperBack: "upper back",
  spine: "spine",
  cardiovascularSystem: "cardiovascular system",
  triceps: "triceps",
  adductors: "adductors",
  hamstrings: "hamstrings",
  glutes: "glutes",
  pectorals: "pectorals",
  calves: "calves",
  lats: "lats",
  quads: "quads",
  abs: "abs",
  neck: "neck",
  femorals: "femorals",
  upperAbs: "upper abs",
};

export const MUSCLE_IMAGES = {
  chest: require("@/assets/images/muscles/chest.png"),
  shoulders: require("@/assets/images/muscles/shoulders.png"),
  biceps: require("@/assets/images/muscles/biceps.png"),
  triceps: require("@/assets/images/muscles/triceps.png"),
  calves: require("@/assets/images/muscles/calves.png"),
  forearms: require("@/assets/images/muscles/forearms.png"),
  abs: require("@/assets/images/muscles/abs.png"),
  lowerAbs: require("@/assets/images/muscles/lower-abs.png"),
  upperAbs: require("@/assets/images/muscles/upper-abs.png"),
  traps: require("@/assets/images/muscles/traps.png"),
  lowerBack: require("@/assets/images/muscles/lower-back.png"),
  glutes: require("@/assets/images/muscles/glutes.png"),
  lats: require("@/assets/images/muscles/lats.png"),
  serratusAnterior: require("@/assets/images/muscles/serratus.png"),
  neck: require("@/assets/images/muscles/neck.png"),
  abductors: require("@/assets/images/muscles/abductors.png"),
  femorals: require("@/assets/images/muscles/femorals.png"),
  obliques: require("@/assets/images/muscles/obliques.png"),
  quads: require("@/assets/images/muscles/quads.png"),

  // obliques2: require("@/assets/images/muscles/obliques-2.png"),
  // quads2: require("@/assets/images/muscles/quads-2.png"),
  // back: require("@/assets/images/muscles/back.png"),
  // legs: require("@/assets/images/muscles/legs.png"),
  // calves2: require("@/assets/images/muscles/calves-2.png"),
  // forearms2: require("@/assets/images/muscles/forearms-2.png"),
  // upperBack: require("@/assets/images/muscles/upper-back.png"),
};
